workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.derbmaroc.battle"
    scripts:
      - cd app
      - gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
